### PR TITLE
Migration to AVRO 1.9.0

### PR DESCRIPTION
**Pull request by plinioj**
Migration to 1.9.0

Mostly small changes like packages and some methods names changes except for the "" in the decimal types

### CODE REVIEW

**Comment by julianpeeters** [comment]
Thank you for the contribution @plinioj !  I expect to have some time to address this in the next couple weeks.

**Comment by leosilvadev** [comment]
@julianpeeters I had to make some changes on that too since we faced issues on the usage of Scavro and the Utf8 type for String.
I personally did not like the implementation but would like to see if you have an idea about how to make it work in a better way. The main issue is that Java class we have are being generated as Utf8 and then on the Scala generated classes by Scavro it was trying to pass a simple String to it. From my understanding we should have two approaches:
- Scala classes should work directly with Utf8 (what I did)
- Scala classes would wrap a normal string to a Utf8 type in the scala classes
My knowledge about how things should work is not so good yet so I expect that maybe there are much better solutions for that issue

Please let me know what you think about it

Cheers

**Comment by julianpeeters** [comment]
Update: The uprgade looks nice, thank you! `Migration to AVRO 1.9.0` `f066d51`.

I'm still thinking about how to best approach UTF8

**Comment by leosilvadev** [comment]
@julianpeeters great! I am going to resolve the conflicts and push it in the next few days

**Comment by julianpeeters** [comment]
slight hangup, I'm sure it's temporary. Looks like decimal defaults in nullable unions might have broken in 1.9.0, this test isn't passing https://github.com/julianpeeters/sbt-avrohugger/commit/e29051e557a19beb0cfa28bc40c6732246f54fb9#diff-7b7509778ee65326108e51aff22d4fcd

I see there was a union regression (with fix coming up), I wonder if this is related. I'll try it when its out http://apache-avro.679487.n3.nabble.com/union-schema-evolution-td4042964.html

**Comment by julianpeeters** [comment]
Thanks again @plinioj and @leosilvadev !

I had some trouble updating all the scripted tests, and ended up cherry picking the avro 1.9 stuff.

If you'd still like to add the customizable string types, that should be done in another PR, likely using the existing system that allows generating into "custom" types:
see https://github.com/julianpeeters/avrohugger/blob/master/avrohugger-core/src/main/scala/types/PrimitiveAvroScalaTypes.scala#L14

enums or arrays might be a good example to follow: https://github.com/julianpeeters/avrohugger/blob/master/avrohugger-core/src/main/scala/types/ComplexAvroScalaTypes.scala#L12

**Comment by julianpeeters** [comment]
avro 1.9.1 available now in avrohugger 1.0.0-RC20

**Pull request closed without merging**
