### PR TITLE
Make `Seq` default type for `array`

### LINKED ISSUE #90: Seq should be favored over List for implementing the Avro Array type
It seems to me that the types in use should be as general as possible, so as to allow for any implementation to be used for a field. As "List" is an implementation of "Seq", "Seq" should be the type  used (or at least be available for use) for the Avro Array. The Avro compiler for Java in fact doesn't use a specific Collection implementation for the Avro Array, but uses the List interface, leaving it open.

I got here because I've run into a problem with Apache Spark trying to deserialize data in Parquet files into classes generated using Avrohugger (using the avrohugger-maven-plugin). Parquet is in fact using Seq to encode Avro Arrays and is trying to assign to List in the Avrohugger-generated case classes.

Here is the error:

> org.apache.spark.sql.AnalysisException: cannot resolve '[list of spark types...]' due to data type $ ismatch: argument 1 requires scala.collection.immutable.List type, however, '[list of spark types...]' is of scala.collection.Seq type.; at org.apache.spark.sql.catalyst.analysis.package$AnalysisErrorAt.failAnalysis(package.scala:42)

Just by way of verification, I re-proved to myself that Seq accepts it's own derivatives, but not vice-versa. (I realize this example is pedantic; that is not my intention - but instead to just share some of my thought process in coming to this.)

Seq allows any Seq derivative
```
@ val seq0: Seq[Int] = Seq(1)
seq0: Seq[Int] = List(1)

@ val seq1: Seq[Int] = List(1)
seq1: Seq[Int] = List(1)

@ val seq2: Seq[Int] = Array(1)
seq2: Seq[Int] = WrappedArray(1)

@ val seq3: Seq[Int] = Vector(1)
seq3: Seq[Int] = Vector(1)
```

Subtypes do not allow assignment of more general types
```
@ val vector0: Vector[Int] = Seq(1)
cmd4.sc:1: type mismatch;
 found   : Seq[Int]
 required: Vector[Int]
val vector0: Vector[Int] = Seq(1)
                              ^
Compilation Failed

@ val vector1: Vector[Int] = Vector(1)
vector1: Vector[Int] = Vector(1)

@ val array0: Array[Int] = Seq(1)
cmd4.sc:1: type mismatch;
 found   : Seq[Int]
 required: Array[Int]
val array0: Array[Int] = Seq(1)
                            ^
Compilation Failed

@ val array1: Array[Int] = Array(1)
array1: Array[Int] = Array(1)

@ val list0: List[Int] = Seq(1)
cmd4.sc:1: type mismatch;
 found   : Seq[Int]
 required: List[Int]
val list0: List[Int] = Seq(1)
           
                ^
Compilation Failed

@ val list1: List[Int] = List(1)
list1: List[Int] = List(1)
```

### PR DESCRIPTION
**Pull request by chrisalbright**
* Add `Seq` type
 * Add spec for `array` type conversions
 * Add test fixture data for `array`
 * Fixes #90

### CODE REVIEW

**Comment by chrisalbright** [comment]
Sorry for the extra commit, I mistakenly created a directory with CapitalLetters in it, and since I'm running OSX with the Case InSensitive filesystem (foolish) I pushed the wrong directory structure.

**Comment by julianpeeters** [comment]
Fantastic @chrisalbright , thanks for the contribution. I expect to have some time to take a closer look this weekend. In the meantime, would you mind adding `sbt scripted` serialization tests? As in https://github.com/julianpeeters/avrohugger#testing
E.g.: https://github.com/julianpeeters/sbt-avrohugger/pull/54/files

You'll have to make sure you've set the version to a SNAPSHOT and publish locally, then bump the dependency in sbt-avrohugger to the snapshot. The whole scripted test suite is getting huge, might as well just run the projects you add or modify like `scripted avrohugger/GenericSerializationTests` etc.

**Comment by chrisalbright** [comment]
@julianpeeters, will do. Sorry for not reading that section closer.

**Comment by chrisalbright** [comment]
@julianpeeters I've added tests for de/serializing in Scavro, SpecificRecord, and Standard (I think that is under `GenericSerializationTests`). They're all passing for me locally, but when I run `scripted avrohugger/ScavroSerializationTests`, I see no tests executed - am I missing something? I'll run the whole suite and submit if it passes, but FYI...

Test output:
>  sbt:sbt-avrohugger> scripted avrohugger/ScavroSerializationTests
[info] Wrote /Users/chris/Dev/avro-scala-stuff/sbt-avrohugger/target/scala-2.12/sbt-1.0/sbt-avrohugger-2.0.0-RC11-SNAPSHOT.pom
[info] Packaging /Users/chris/Dev/avro-scala-stuff/sbt-avrohugger/target/scala-2.12/sbt-1.0/sbt-avrohugger-2.0.0-RC11-SNAPSHOT.jar ...
[info] Done packaging.
[info] :: delivering :: com.julianpeeters#sbt-avrohugger;2.0.0-RC11-SNAPSHOT :: 2.0.0-RC11-SNAPSHOT :: integration :: Tue Jun 26 10:40:13 PDT 2018
[info] 	delivering ivy file to /Users/chris/Dev/avro-scala-stuff/sbt-avrohugger/target/scala-2.12/sbt-1.0/ivy-2.0.0-RC11-SNAPSHOT.xml
[info] 	published sbt-avrohugger to /Users/chris/.ivy2/local/com.julianpeeters/sbt-avrohugger/scala_2.12/sbt_1.0/2.0.0-RC11-SNAPSHOT/poms/sbt-avrohugger.pom
[info] 	published sbt-avrohugger to /Users/chris/.ivy2/local/com.julianpeeters/sbt-avrohugger/scala_2.12/sbt_1.0/2.0.0-RC11-SNAPSHOT/jars/sbt-avrohugger.jar
[info] 	published sbt-avrohugger to /Users/chris/.ivy2/local/com.julianpeeters/sbt-avrohugger/scala_2.12/sbt_1.0/2.0.0-RC11-SNAPSHOT/srcs/sbt-avrohugger-sources.jar
[info] 	published sbt-avrohugger to /Users/chris/.ivy2/local/com.julianpeeters/sbt-avrohugger/scala_2.12/sbt_1.0/2.0.0-RC11-SNAPSHOT/docs/sbt-avrohugger-javadoc.jar
[info] 	published ivy to /Users/chris/.ivy2/local/com.julianpeeters/sbt-avrohugger/scala_2.12/sbt_1.0/2.0.0-RC11-SNAPSHOT/ivys/ivy.xml
Running avrohugger / ScavroSerializationTests
[info] + avrohugger / ScavroSerializationTests
[success] Total time: 1 s, completed Jun 26, 2018 10:40:14 AM

**Comment by julianpeeters** [comment]
@chrisalbright oh that's right, scavro scripted tests are skipped for now, since they use the sbt-avro plugin as well as sbt-avrohugger, and sbt-avro has a file-sorting bug that causes some nested records to fail based on their filenames and fs (OSX vs Linux). There is a fix for sbt-avro now, but it's only merged not yet released AFAIK, so feel free to ignore the scavro tests for now

**Pull request merged**
