### PR TITLE
AVDL support

### PR DESCRIPTION
**Pull request by mariussoutier**
Simple support for AVDL files. At the moment it will ignore the protocol itself, but create the schema classes.

### CODE REVIEW

**Comment by julianpeeters** [comment]
high five.

**Comment by mariussoutier** [comment]
:) Can you cut a new release?

**Comment by julianpeeters** [comment]
Certainly. `avrohugger 0.1.0` and `sbt-avrohugger 0.0.2` should both be syncing with maven central in a few hours.

Heads, up tho, [this](https://github.com/julianpeeters/avrohugger/issues/2) schema-reuse issue can be a nasty one if your code uses `myRecord.getSchema()` for every record (e.g. for the Kafka schema registry).

It's an easy fix to generate a companion object that holds the schema, maybe I'll have one this weekend if you don't get to it first.

**Comment by mariussoutier** [comment]
That would be great! Currently I use MyRecord.SCHEMA$ directly with Twitter Bijection, but the schema registry will certainly be important eventually.

**Pull request merged**
