### PR TITLE
replace JavaConversions with JavaConverters (as former class is deprecated in 2.12.0)

### LINKED ISSUE #49: Use JavaConverters insetad of JavaConversions
starting from 2.12.0 classes generated by avrohugger will produce a warning (or an error if `-Xfatal-warnings` is enabled, which is not unusual)

```
object JavaConversions in package collection is deprecated (since 2.12.0): use JavaConverters
[error]             scala.collection.JavaConversions.mapAsScalaMap(map).toMap map { kvp =>
```

I can send a PR sometime this week

### PR DESCRIPTION
**Pull request by jozic**
unit tests pass, but as i mentioned on gitter, some of scripted tests are failing for me even on master branch

@julianpeeters please review and let me know if scripted runs for you.

Thanks

fixes #49

### CODE REVIEW

**Comment by jozic** [comment]
@julianpeeters do you wanna review/merge this? 2.12.0 is already out :)

**Comment by julianpeeters** [comment]
Hey @jozic, thanks for your patience on this. `scripted` tests are now passing for me on Linux on `master`, however some errors are revealed on `scripted` after pulling in this PR (and publishing local, then bumping sbt-avrohugger and publishing that locally). 

for example:

```
[info] [error] /tmp/sbt_743b95eb/SpecificVectorSerializationTests/target/scala-2.10/src_managed/main/compiled_avro/test/AvroType
ProviderTest62.scala:29: value asScalaIterator is not a member of object scala.collection.JavaConverters
[info] [error]             Vector((scala.collection.JavaConverters.asScalaIterator(array.iterator).toSeq map { x =>
[info] [error]
```

Seems simple enough to fix. If you don't beat me to it, I think I'll finally have some more time this coming weekend.

Cheers

**Comment by jozic** [comment]
@julianpeeters 
thanks for checking it out. i will look into it in couple days, probably before next week

**Comment by jozic** [comment]
@julianpeeters this time i was able to run scripted tests on latest master
so i've rebased my branch on latest master, runs scripted and observed errors you mentioned, fixed them and now scripted tests are green. at least for me :)

please check it again
thanks

**Comment by julianpeeters** [comment]
Awesome, nice work @jozic. This is out now in avrohugger/sbt-avrohugger version 0.13.0

**Comment by jozic** [comment]
thanks for releasing it!

**Pull request merged**
