### PR TITLE
Add support for UUIDs

### PR DESCRIPTION
**Pull request by agustafson**

### CODE REVIEW

**Comment by julianpeeters** [comment]
Fantastic contribution @agustafson, I imagine this will make people very happy.

Would you be able to take on the addition of some `scripted` serialization tests, to confirm the generated types behave as expected? (i.e. adding to the [existing specs for `Standard` format](https://github.com/julianpeeters/sbt-avrohugger/blob/master/src/sbt-test/avrohugger/GenericSerializationTests/src/test/scala/test/standard/StandardPrimitivesSpec.scala#L91-L122) from [avdl](https://github.com/julianpeeters/sbt-avrohugger/blob/master/src/sbt-test/avrohugger/GenericSerializationTests/src/main/avro/logical.avdl) and [avsc](https://github.com/julianpeeters/sbt-avrohugger/blob/master/src/sbt-test/avrohugger/GenericSerializationTests/src/main/avro/logical.avsc), and [existing specs for `SpecificRecord` format](https://github.com/julianpeeters/sbt-avrohugger/blob/master/src/sbt-test/avrohugger/SpecificSerializationTests/src/test/scala/specific/SpecificPrimitivesSpec.scala#L79-L95) from [avdl](https://github.com/julianpeeters/sbt-avrohugger/blob/master/src/sbt-test/avrohugger/SpecificSerializationTests/src/main/avro/logical.avdl) and [avsc](https://github.com/julianpeeters/sbt-avrohugger/blob/master/src/sbt-test/avrohugger/SpecificSerializationTests/src/main/avro/logical.avsc))

**Comment by agustafson** [comment]
Happy to contribute, thanks for your great work on avrohugger 😀 
I'll add some of scripted tests sometime this week if i get a chance, but I don't believe that the uuid logicalType is supported by avdl: https://avro.apache.org/docs/1.8.2/idl.html#logical_types

**Comment by agustafson** [comment]
Good shout on running the scripted tests @julianpeeters - I found an error as it couldn't handle `org.apache.avro.util.Utf8`s. Have updated this PR to handle all `java.lang.CharSequence`s.

**Comment by julianpeeters** [comment]
Awesome @agustafson, this is up at sonatype now as avrohugger version 1.0.0-RC13 and sbt-avrohugger version 2.0.0-RC13, expected to sync up with maven central shortly.

**Comment by agustafson** [comment]
Fantastic! Thanks for giving such quick feedback and approving so quickly @julianpeeters. And the level of testing in `sbt-avrohugger` is really impressive. Makes it easier to make contributions to the project 👍

**Pull request merged**
