### PR TITLE
Add avrohugger-filesorter module

### PR DESCRIPTION
**Pull request by makubi**
Extracted from
https://github.com/julianpeeters/sbt-avro/tree/ebf8309223eedf716d36f2dc3c973d37fca58b81/src/main/scala/sbtavro/filesorter

### CODE REVIEW

**Comment by julianpeeters** [comment]
Very cool @makubi, was hoping to get this merged this weekend but didn't quite get to it. I'll revisit ASAP.

**Comment by makubi** [comment]
Nice, sure, no hurry on this!

**Comment by makubi** [comment]
@julianpeeters I updated the files to the latest version from https://github.com/julianpeeters/sbt-avrohugger

**Comment by mariussoutier** [comment]
:+1:

**Comment by julianpeeters** [comment]
Thanks again for the legwork guys, I finally had a chance to release this as avrohugger 0.16.0

**Pull request merged**
