### PR TITLE
Bumps Avro

### PR DESCRIPTION
**Pull request by fedefernandez**
This PR bumps apache avro to 1.9.0

**Notes/Caveats**

The `Schema.defaultValue` is now protected and the alternative method, `defaultVal` returns the mapped object, instead of the node. To solve this I've moved the `DefaultValueMatcher` to the package `org.apache.avro`

Screenshot 2019-07-19 at 16 25 38

After the changes, the tests were failing with the following error:

```
java.lang.RuntimeException: Unexpected exception: org.apache.avro.AvroTypeException: Invalid default for field dec: 8888.88 not a {"type":"bytes","logicalType":"decimal","precision":9,"scale":2} (StringInputParser.scala:64)
```

Looking for an explanation, I found this in the [avro docs](https://avro.apache.org/docs/1.8.1/spec.html#schema_complex) saying that the default values for bytes should be `String`s

Screenshot 2019-07-19 at 16 23 19

I've changed the AVDL definitions and the `DefaultValueMatcher` to fulfill that.

https://github.com/julianpeeters/avrohugger/compare/master...fedefernandez:bump-libs?expand=1#diff-61e4ffe788fccaab998b4148f2070543R65

### CODE REVIEW

**Comment by julianpeeters** [comment]
thanks @fedefernandez ! I ran out of time this weekend, but I expect to merge this by the end of next weekend.

**Comment by fedefernandez** [comment]
@julianpeeters no problem, whenever you have a chance it's fine. Do you think the BigDecimal default values could cause some issues? Should we add some notes in the release?

**Comment by julianpeeters** [comment]
@fedefernandez I think that the scripted tests in sbt-avrohugger might need an update as well. Have you happened to try yet? I expect to have some time next weekend to take a look.

Regarding the BigDecimal defaults possibly causing problems
 - I'm hoping that the avro compiler's validation will alert people that they need to fix any idls that used avrohugger as their example
 - and that the bump to avrohugger 1.9.0 makes the change easier to take
 - I'll also going to take advantage of the `RC` status to accommodate the changes

**Comment by fedefernandez** [comment]
@julianpeeters I always forget the scripted test. I'm expecting to have some time before the end of the week. I'll take a look.

**Comment by julianpeeters** [comment]
Hey @fedefernandez! I think avro 1.9.0 may have broken decimal default values in nullable unions? This fails for me unless I add a third member to the union or use a type other than decimal https://github.com/julianpeeters/sbt-avrohugger/commit/e29051e557a19beb0cfa28bc40c6732246f54fb9#diff-7b7509778ee65326108e51aff22d4fcd

I see there was a union regression (with fix coming up), I wonder if this is related. http://apache-avro.679487.n3.nabble.com/union-schema-evolution-td4042964.html

**Comment by fedefernandez** [comment]
@julianpeeters I've been taking a look to your branch. It compiles, passes the tests but the `scripted` task never finishes, it gets stuck here:

```scala
[info] [info] Updating ...
[info] [info] Done updating.
[info] [info] Considering source directories /private/var/folders/74/dkxltt951zs5pjkc8tybgh700000gn/T/sbt_f44187fc/standard/src/main/avro,/private/var/folders/74/dkxltt951zs5pjkc8tybgh700000gn/T/sbt_f44187fc/standard/src/main/avro2
[info] [info] Compiling AVSC /private/var/folders/74/dkxltt951zs5pjkc8tybgh700000gn/T/sbt_f44187fc/standard/src/main/avro2/testAVSC.avsc to /private/var/folders/74/dkxltt951zs5pjkc8tybgh700000gn/T/sbt_f44187fc/standard/target/scala-2.12/src_managed/main/compiled_avro
[info] [info] Compiling AVSC /private/var/folders/74/dkxltt951zs5pjkc8tybgh700000gn/T/sbt_f44187fc/standard/src/main/avro/testAVSC.avsc to /private/var/folders/74/dkxltt951zs5pjkc8tybgh700000gn/T/sbt_f44187fc/standard/target/scala-2.12/src_managed/main/compiled_avro
```

Do you have by a chance the output error? Thanks

**Comment by julianpeeters** [comment]
@fedefernandez I wonder if your cache is clogged with an older version? (That folder is familiar from some classpath checking in avrohugger in RC16, and also maybe relevant, a classloader bug in the plugin that was fixed in RC17)

here's the error I get (I didn't notice the other errors before, I guess I was doing `testOnly`): https://travis-ci.org/julianpeeters/sbt-avrohugger/jobs/567644090#L2905

**Comment by fedefernandez** [comment]
@julianpeeters do you think it could be a binary incompatibility problem? 

I can find some `avro-ipc` dependencies still in `1.7.7` and the `avro4s` dependency that is still tied to `avro` 1.8.x. 

I've created a PR with the missing dependencies. I can't execute the scripted tests locally, I've tried cleaning the *local ivy* and all the project's targets without no luck. 

This is the PR: https://github.com/julianpeeters/sbt-avrohugger/pull/74

Thanks for your time.

**Comment by julianpeeters** [comment]
Ah thanks @fedefernandez, I suppose that could be the case. I'll try that when I get a chance.

And sorry you've been having trouble running tests, sounds frustrating! Just to confirm, in your local ivy, I wonder if you've tried manually deleting `.ivy/cache/com.julianpeeters`, in a addition to `.ivy/local/com.julianpeeters`? I'm double checking because this change would seem to be another clue that an old version of avrohugger is being picked up somehow https://github.com/julianpeeters/sbt-avrohugger/pull/74/files#diff-7c9f933f4d1c7cedd94a44e3defbe648L91

**Comment by julianpeeters** [comment]
Thanks again for the help on this @fedefernandez. I was finally able to get upgraded to avro 1.9.1, out now in avrohugger 1.0.0-RC20
 
Note (especially the second one):
1. in the scripted tests, to test the generated files, I had to trim back and change some tests to use java GenericRecord.  Avro4s 3.0 is apparently a little broken on bigdecimals in certain contexts, and similarly default coproducts seem to have no quick fix.
2. avro 1.9 apparently got more strict and validates more. Revealed that avrohugger's test examples were wrong for default decimals (they should be Strings, yes, but bytes like "\u00C6", not a decimal String). Avro4s was affected too. Seems to be a common gotcha http://mail-archives.apache.org/mod_mbox/avro-dev/201812.mbox/%3CJIRA.13107261.1507216833000.25125.1546148580244@Atlassian.JIRA%3E

**Comment by fedefernandez** [comment]
thanks for your efforts @julianpeeters, good findings!

**Pull request closed without merging**
