### PR TITLE
Support Enums

### PR DESCRIPTION
**Pull request by mariussoutier**
Here's a PR that supports enums by generating scala.Enumeration. It's referenced in other records via `$EnumName.$EnumName`.

Code is not perfect yet, emits match exhaustiveness warning because I have to decide between RECORD and ENUM.

### CODE REVIEW

**Comment by julianpeeters** [comment]
This is a great effort! Two concerns that didn't foresee:

(1.) Case classes can be serialized efficiently because the costly/heavy schema is kept in the static companion object.

Will a record with an enum field serialize efficiently? Since it's being represented as an object, we can't pull the same trick as with the case class described above, so will the $SCHEMA val of the object inflate the record/message size by ~1000 bytes?

(2.) The scripted DatatypeSerializationTests seems to fail upon deserilization ([see this branch](https://github.com/julianpeeters/avrohugger/tree/enum_error)). 

First a word about the confusing testing layout:

I don't know of a better way to automate testing if the generated source code can actually be used to de/serialize. Currently avrohugger uses the `scripted` task to run projects that depend on the `sbt-avrohugger` plugin. To be explicit, the steps are (and I'll make this more clear in the readme):

(a.) bump avrohugger to SNAPSHOT

(b.) add feature to avrohugger

(c.) test if code gen looks correct and can compile

(d.) avrohugger publish local

(e.) bump sbt-avrohugger to SNAPSHOT

(f.) update sbt-avrohugger to depend on new avrohugger SNAPSHOT

(g.) optionally update sbt-avrohugger to support new feature (e.g., needed for .avdl support, but not for `enum`)

(h.) sbt-avrohugger publish local 

(i.) finally, in `avrohugger` now run `scripted` to run all tests, including the tests in project folder `sbt-test/projects/DatatypeSerializationTests` 
- or finally just `cd` into the project folder and run `sbt test` to do the same thing as (i.) more quickly.

Like I said, as convoluted as this is, I'm very open to suggestions; it's just the best way I know to keep this essential integration test bundled in the same project as the code that determines its success. 

The DatatypeSerializationTests of the `enum` datatype give the following error upon deserialization:

```
 A case class with a `Enumeration` field should

[info] ! serialize and deserialize correctly
[error]    IllegalArgumentException: : test.Direction is not an enum type  (SpecificData.java:106)
[error] org.apache.avro.specific.SpecificData.createEnum(SpecificData.java:106)
[error] org.apache.avro.generic.GenericDatumReader.createEnum(GenericDatumReader.java:205)
[error] org.apache.avro.generic.GenericDatumReader.readEnum(GenericDatumReader.java:199)
[error] org.apache.avro.generic.GenericDatumReader.read(GenericDatumReader.java:152)
[error] org.apache.avro.generic.GenericDatumReader.readField(GenericDatumReader.java:193)
[error] org.apache.avro.generic.GenericDatumReader.readRecord(GenericDatumReader.java:183)
[error] org.apache.avro.generic.GenericDatumReader.read(GenericDatumReader.java:151)
[error] org.apache.avro.generic.GenericDatumReader.read(GenericDatumReader.java:142)
[error] org.apache.avro.file.DataFileStream.next(DataFileStream.java:233)
[error] org.apache.avro.file.DataFileStream.next(DataFileStream.java:220)
[error] SpecificEnum01Test$$anonfun$17$$anonfun$apply$65.apply(PrimitivesSpec.scala:471)
[error] SpecificEnum01Test$$anonfun$17$$anonfun$apply$65.apply(PrimitivesSpec.scala:451)
```

The code referred to from Avro's SpecificData

```
   public Object createEnum(String symbol, Schema schema) {
    Class c = getClass(schema);
    if (c == null) return super.createEnum(symbol, schema); // punt to generic
    return Enum.valueOf(c, symbol);
  }
```

I'm not sure exactly what's going on here, although I'll be able to look more closely tonight, and I do have some guesses.

Do you have any insight how to fix this?

I'll note that:
- often using Java's Enum is preferred when writing Scala libraries that interact with Java
- on the other hand, [Avro seems to encourage](https://github.com/apache/avro/blob/branch-1.7/lang/java/avro/src/main/java/org/apache/avro/generic/GenericData.java#L1017) alternate representations of enum. If have no problem supporting whatever actually works, or both if people want them and if support for both can be accomplished cleanly.
- The root of the error the fact that the wrong kind of enum was made?
- Or was it that there was no class found for Avro tried to reflectively find `Direction` when it should be looking for `Direction$`, and thus dropped through from Specific to Generic? Wouldn't be the first time Avro's assumption of a Java environment has presented a roadblock.

Interesting challenges!

**Comment by julianpeeters** [comment]
Update: 

On closer inspection it seems that enum fell through to the Generic API before it was written, and was only written because it slipped through the cracks. The Generic API becomes more strict in Avro 1.8.0, and even writing this style of enum fails ([relevant discussion](https://issues.apache.org/jira/browse/AVRO-997)). 

Are Scala enums any better than Java enums? (Scala case classes as RECORD and Java enums as ENUM works fine.)

With respect to Avro supporting alternative enum implementations, how is that done? The link in this comment seems to suggest `GenericData.enumSymbol(schema: Schema, symbol: String)` for use with SpecificRecord? (That same link starts a long time ago and also says that plain Java enum won't work in SpecificRecords, when clearly now it does, so take that link with a grain of salt)

**Comment by mariussoutier** [comment]
Sorry I didn't run the sbt-avro integration tests. I only did that for the sbt-avro commits I made, but had somehow hoped the units tests would suffice this time. Obviously that assumption was wrong and would have pointed me to the error sooner.

I made a local snapshot release and tested it in my project. While the generated code looks fine, Twitter Bijection also cannot deserialize it (serializing works fine). Unfortunately it doesn't give a real error message but I guess it's the same one.

Originally I just looked at how Avro generates Java classes from specific records, and Java enums don't implement any interface at all, the only have the `SCHEMA$` field.

To address your points:
- Re SCHEMA$ field: How can I check what fields get serialized? When I look at the JSON representation, I only see the data. Is this an issue with Avro?
- You are certainly right that the code you quoted from SpecificData tries to instantiate a Java enum, and that obviously fails.
- Scala enums are not better than Java enums, it was just an attempt to avoid mixing Java and Scala code.
- If the simplest solution is to create Java enums, maybe that's the way to go.
- Alternatively, how can we override `GenericData.enumSymbol` / `SpecificData.createEnum`?

**Comment by julianpeeters** [comment]
If neither Java enums nor Scala enums are superior, then I agree that mixing Java and Scala code would be nice to avoid (for users and maintainers I suppose).

It turns out that it's not too hard to convert Scala enums into `GenericData.EnumSymbols` which work in SpecificRecords.

in the get method, `suit` must be converted like  
`new org.apache.avro.generic.GenericData.EnumSymbol(Direction.SCHEMA$, direction)`

and in the put method, `value` should be `Suit.withName(value.toString)`

like so:

``` scala
/** MACHINE-GENERATED FROM AVRO SCHEMA. DO NOT EDIT DIRECTLY */
package test

case class Compass(var direction: Direction.Value) extends org.apache.avro.specific.SpecificRecordBase {
  def this() = this(null)
  def get(field: Int): AnyRef = {
    field match {
      case pos if pos == 0 => {
        new org.apache.avro.generic.GenericData.EnumSymbol(Direction.SCHEMA$, direction)
      }.asInstanceOf[AnyRef]
      case _ => new org.apache.avro.AvroRuntimeException("Bad index")
    }
  }
  def put(field: Int, value: Any): Unit = {
    field match {
      case pos if pos == 0 => this.direction = {
        Direction.withName(value.toString)
      }.asInstanceOf[Direction.Value]
      case _ => new org.apache.avro.AvroRuntimeException("Bad index")
    }
    ()
  }
  def getSchema: org.apache.avro.Schema = Compass.SCHEMA$
}

object Compass {
  val SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Compass\",\"namespace\":\"test\",\"fields\":[{\"name\":\"direction\",\"type\":{\"type\":\"enum\",\"name\":\"Direction\",\"symbols\":[\"NORTH\",\"SOUTH\",\"EAST\",\"WEST\"]}}]}")
}
```

The record size issue was brought to my attention in the macros project, [this gist](https://gist.github.com/vidma/cefce783108ed3946b7c) showing that it got fixed there.

I checked in Avro and looks like the whole record is represented as 1 byte, so I'd say it's working.

My experiments were in a separate project, and it's late here, so tomorrow evening I'll be happy to update the project if you haven't discovered all of this yourself already.

**Comment by mariussoutier** [comment]
Nice, thanks!

I'll update the PR and try the tests and Bijection. Will report back later (here it's mid-day, so still time left).

**Comment by mariussoutier** [comment]
Unfortunately, returning `GenericData.EnumSymbol` doesn't seem to solve the problem, same error as before. 

When I manually edit the schema in the classes of records to to use `.Value`, de/serialization works. 

However it seems impossible to add this to the Avro schema. I have tried rewriting the schema of the fields, but a dot-name always gets separated into namespace and name, so `"name":"Compass.Value"` is being interpreted as `"name":"Value","namespace":"Compass"`.

I have looked into the implementation and even though you can specify name and namespace separately, it gets merged eventually and they just do a String split on the dots (d'oh).

**Comment by julianpeeters** [comment]
Dang. My bad, I'd forgotten that I'd altered to my local version of SpecificData to always punt to Generic. 

Given the strictness of SpecificData's createEnum, and your exploration the schema alteration route, I suspect that the case objects/sealed trait Scala Enum strategy would also fail?

I think I'll take a stab at generating Java enums with Avro's SpecificCompiler.

**Comment by mariussoutier** [comment]
I also thought about trying out sealed traits, but I guess the same problem would apply. Also it might be harder to re-create the specific case object from the serialized bytes (just a guess).

I agree, using a Java enum seems to be our best bet right now. 

Btw. I've opened a ticket on the Avro JIRA to better support Scala by not only relying on a public `SCHEMA$` field, but who knows if they'll change that.

**Comment by julianpeeters** [comment]
Ha, nice ticket. That's a great, easy solution.

I've updated the [enum_error](https://github.com/julianpeeters/avrohugger/tree/enum_error) branch, almost working.

For the `generate` task, I left the scala.Enumeration strategey, and it works well with Scalavro and Salat-Avro (for the few people who have a non-SpecificRecord use case).

For the `generate-specific` task, there is one remaining issue: *.java and *.scala files can't be compiled in in the same directory together - the Scala compilation can't see the Java types. 

My naive first attempt was to put the Java and Scala sources in dedicated `baseDir/java` and `baseDir/scala` directories, but that didn't seem to help.

**Pull request merged**
